export const gitHubRepoTypes = {
    GITHUB_REPO_LIST_REQUEST : 'GITHUB_REPO_LIST_REQUEST',
    GITHUB_REPO_LIST_SUCCESS : 'GITHUB_REPO_LIST_SUCCESS',
    GITHUB_REPO_LIST_FAIL : 'GITHUB_REPO_LIST_FAIL',
}